### PR TITLE
Fix messybrainz text/colours

### PR DESCRIPTION
**Pull request by alastair**
The MessyBrainz section must have been copied from AB, the colours were updated but not all of the text

### CODE REVIEW

**Comment by reosarevok** [comment]
I thought MessyBrainz wasn't a thing anymore anyway? :)

**Comment by alastair** [comment]
long live messybrainz

(the stickers still look great, so I vote we keep it!)

**Comment by Aerozol** [comment]
Thank you!

I didn’t (and largely don’t) know what’s going on with a bunch of projects, so I just added everything. Guidelines for OfficeBrainz are probably a bit unnecessary as well hah.

**Review by Aerozol — APPROVED** [review]

**Comment by akshaaatt** [comment]
@Aerozol Should we remove MessyBrainz altogether now that it is a part of ListenBrainz directly?

**Comment by mayhem** [comment]
Could we move that to a "historical" folder, so that we don't actually have these assets disappear from view? NGL, but the messybrainz logo is one of my favorites and I am sad to see it go.

**Comment by akshaaatt** [comment]
Sounds reasonable to me @mayhem. @Aerozol has already managed the folders nicely and kept teh retired logos here at https://github.com/metabrainz/design-system/tree/master/brand/logos/_development/retired

**Comment by mayhem** [comment]
Purrrrfect, thanks!

**Comment by akshaaatt** [comment]
Given that AcousticBrainz and MessyBrainz are not a part of the design guidelines anymore and have been moved to the retired folder, it makes sense to close this PR.

**Pull request closed without merging**
