### PR TITLE
Create MusicBrainzWiki_logo_factory.ai

### PR DESCRIPTION
**Pull request by Aerozol**
Added MBWiki logo

### CODE REVIEW

**Review by akshaaatt — COMMENTED** [review]
Aren't we planning to include the svg and png for this?

**Comment by Aerozol** [comment]
Thanks Akshaaatt, no - this is a one-off, and I didn’t want to clutter the folder structure with it. But I think the working file (that everything else can be derived from) should be there just in case. Does that make sense?

**Review by yvanzo — COMMENTED** [review]
Having a different icon from `musicbrainz.org` helped to distinguish the wiki pages from their corresponding MusicBrainz documentation pages in tabs.

For example:
* https://wiki.musicbrainz.org/WikiDocs
* https://musicbrainz.org/doc/WikiDocs

Since the MusicBrainz Wiki is also used a bit for MetaBrainz stuff, would it make sense to replace the MB purple background color with a green/purple pattern (checks, or stripes, or beams…)?

If only the AI file is provided, then there is no track of the PNG/SVG versions used for the wiki but in backups.

**Comment by Aerozol** [comment]
yvanzo, I’ve re-opened the relevant ticket with your comments:
https://tickets.metabrainz.org/browse/MBH-542

I will mockup some different icons for discussion there, if you would like to follow and comment

**Pull request closed without merging**
