### PR TITLE
Bumped Dependencies and Fix Configurations

### PR DESCRIPTION
**Pull request by akshaaatt**
- The project needs to be bumped before we add major changes.

### CODE REVIEW

**Comment by mwiencek** [comment]
Did you test running the project with the new dependencies? (Not sure if the Webpack upgrade in particular requires changes.)

**Comment by akshaaatt** [comment]
Finally verified and all working!
Preview available at https://61ec89ab79aea5003a4ece24-kskqlfpzms.chromatic.com

**Comment by mwiencek** [comment]
Thanks!  For the future, try to make your commit messages more descriptive, or squash them together if they were WIP and constitute a single change in the end.  For example, https://github.com/metabrainz/design-system/commit/0174a0548ac102ebdc5dfa6a337b36ecdc282440 has a commit message explaining why some lines of scss/bootstrap-prod.scss were commented out.  Some of the commits here changed that and then reverted the changes, but there's no explanation other than "cleanup" and "fix."

There are also a lot of unrelated changes in each commit here.  Ideally each commit should do one thing.  That makes it much easier for other team members to review and use tools like `git bisect` and `git blame` in the future.  This has some good tips: https://reflectoring.io/meaningful-commit-messages/

**Comment by akshaaatt** [comment]
Makes sense. Will do so in future!👌

**Pull request merged**
