### PR TITLE
MEB-132: Added MetaBrainz and MusicBrainz guidelines to discuss

### PR DESCRIPTION
**Pull request by Aerozol**

### CODE REVIEW

**Review by yvanzo — COMMENTED** [review]
It looks brilliant overall. Thank you for having taken the time to go through projects to find their inconsistencies and unwritten conventions. Comments and suggestions:

1. Guidelines file format:
    - PDF is great for the print, not for the web. These guidelines will be mainly read on screen.
    - Comparing and commenting binary files is not easy using respectively Git and GitHub.
    - The current side-by-side display makes the text way too small to read on a laptop screen.
    - The alt text generated by `pdftotext` isn’t clean and doesn’t include images.

   It would be nice to have Markdown files instead. Markdown is a text format you already started to use and supports the inclusion of images. Full reference on GitHub: “[Mastering Markdown](https://guides.github.com/features/mastering-markdown/)”.

2. Typefaces:
   - If there is a rationale behind the choice of Roboto/Sintony, it should probably be mentioned.
   - It seems that DejaVu (superset of Bitstream Vera) is (unfortunately not consistently) used in MusicBrainz website at least because it has a good Unicode coverage and is under a free license.

3. MusicBrainz-only page elements:
   - Thanks for making this explanatory description of the current layout!
   - a. also features the language selector.
   - g. is empty in your screen capture.

4. Minor: I’m not used to “useage”, might not be only me, “usage” seems to be more common.

**Comment by Aerozol** [comment]
Thanks for the feedback! Changes will be in the next version once I sort out my erroneous extra commits...

yvanzo:
- 'language selector' might be added to the footer soon I think, so I haven't changed that for now. Hopefully it's covered by 'important links covered on every page'
- I don't know if there is a rationale for using Roboto/Sintony, it's taken from the newer projects. Maybe Monkey can help - I'm open to using different fonts entirely, it's been extremely hard to pin anyone down to discuss this tbh
- File format: I would like to copy this into readme once it's been finalised. But it should _not_ be regularly edited so I want a static PDF as well. I went with PDF to start because that is comfortable for me and Akshat gave the ok to change it later
- changed to usage, sorry I didn't already do this, thanks for bringing it up again!

monkey:
- keen to have a lot of freedom with gradients, I tweaked a few already - but I had no idea if there was appetite to use them for other projects at all so I didn't go too deep. BB is going to be tricky, but maybe I'm overthinking it. Here's screenshots comparing BB + MB / BB + OB / Halloween: https://drive.google.com/file/d/1C8ydhr6AMhIb0eo_xR5EjE5tmIfj3nC6/view?usp=sharing
- CAA gradient fixed
- icon mini version fixed, thanks for bringing this up again
- any thoughts on fonts, see yvanzo's note

**Comment by zas** [comment]
I totally agree with @yvanzo regarding PDF format, it doesn't allow easy tracking of changes, I think we should stay with Markdown (and convert to PDF from that).

**Review by akshaaatt — COMMENTED** [review]
I have picked the guidelines from the pdf files and set them up in an MD file for clear understanding.

I would like to point out that the two separate pdf files have a lot of similar content, which should be taken care of. I am not sure whether MetaBrainz and MusicBrainz guidelines should be separate. We can follow one guideline.

**Review by akshaaatt — APPROVED** [review]

**Comment by Aerozol** [comment]
Not sure if everyone receives notifications from comments - the text file guidelines are all up to date and have been merged by akshaaatt, but further feedback is welcome.

I had the same question re. multiple guidelines/a guideline for each project akshaaatt, but I found it was necessary because I really struggled to combine everything, as the projects are quite different - you'll notice the MetaBrainz and MusicBrainz guideline PDFs are quite different to each other.

**Pull request merged**
